import { TYPE_PARTICIPANT } from "./participant";
import { TYPE_SCHEDULE } from "./schedule";
import { TYPE_ADDRESS } from "./address";

export type TYPE_REQUEST = {
  id?: number;
  addresses: TYPE_ADDRESS[] | [];
  participants: TYPE_PARTICIPANT[] | [];
  schedules: TYPE_SCHEDULE[] | [];
  advantages: null | string;
  age_min: null | number;
  age_max: null | number;
  age_checked: boolean;
  company: null | string;
  contacts: null | string;
  date: null | string;
  date_open: null | string;
  date_close: null | string;
  date_publication: null | string;
  date_archive: null | string;
  department: null | string;
  education: null | number;
  education_checked: boolean;
  employees_quantity: null | number;
  employment_type: null | number;
  experience: null | number;
  functional: null | string;
  name_of_position: null | string;
  name_of_position_checked: boolean;
  name_of_vacancy: null | string;
  offering: null | string;
  salary_gross: null | number;
  salary_min: null | number;
  salary_max: null | number;
  salary_show: null | number;
  salary_checked: boolean;
  sex_value: null | number;
  sex_value_checked: boolean;
  status: null | number;
  wishes: null | string;
  sono: null | string;
  createdAt?: string;
  updatedAt?: string;
};
